title: LF Energy Foundation TAC
description: Materials and processes for the LF Energy Foundation TAC
logo: "https://artwork.lfenergy.org/other/lf-energy/horizontal/color/lf-energy-horizontal-color.svg"
theme: just-the-docs

exclude: [
  "README.md",
  "completed.md",
  "dco-signoffs/",
  "Gemfile", 
  "Gemfile.lock", 
  "package.json", 
  "package-lock.json",
  "CODE_OF_CONDUCT.md",
  "LICENSE"
]

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/lf-energy/tac" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree"

landscape_url: 'https://landscape.lfenergy.org'
calendar_url: 'https://calendar.lfenergy.org'
slack_url: 'https://slack.lfenergy.org'
membership_top_tier: 'Strategic'
foundation_name: 'LF Energy Foundation'

aux_links:
  "Need help or have a question? Contact us here":
    - "//servicedesk.lfenergy.org"
footer_content: Copyright &copy; The Linux Foundation&reg;. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/trademark-usage">Trademark Usage</a> page. Linux is a registered trademark of Linus Torvalds. <a href="http://www.linuxfoundation.org/privacy">Privacy Policy</a> and <a href="http://www.linuxfoundation.org/terms">Terms of Use</a>.

readme_index:
  with_frontmatter: true
  

kramdown:
  input: GFM
  extensions:
    - autolink
