title: LF Energy Foundation TAC
description: Materials and processes for the LF Energy Foundation TAC
logo: "https://artwork.lfenergy.org/other/lf-energy/horizontal/color/lf-energy-horizontal-color.svg"
theme: just-the-docs
repository: lf-energy/tac

exclude: [
  "README.md",
  "completed.md",
  "dco-signoffs/",
  "Gemfile", 
  "Gemfile.lock", 
  "package.json", 
  "package-lock.json",
  "CODE_OF_CONDUCT.md",
  "LICENSE",
  "vendor"
]

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/lf-energy/tac" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree"

# Various URLs used across the site
landscape_url: 'https://landscape.lfenergy.org'
calendar_url: 'https://calendar.lfenergy.org'
slack_url: 'https://slack.lfenergy.org'
directed_fund_charter_url: 'https://charter.lfenergy.org'
tac_issues_url: 'https://github.com/lf-energy/tac/issues/new'
helpdesk_url: "https://servicedesk.lfenergy.org"
mailing_list_url: "https://lists.lfenergy.org"
wiki_url: "https://wiki.lfenergy.org"
lfx_insights_url: "https://insights.lfx.linuxfoundation.org/foundation/lfenergy"
tac_mailing_list_url: "https://lists.lfenergy.org/g/tac"
website_url: "https://lfenergy.org"
blog_url: "https://lfenergy.org/blog"
tac_lfx_meeting_url: https://zoom-lfx.platform.linuxfoundation.org/meeting/95214651568?password=eda16f17-bdd1-4a9f-a594-0947a1433153
lfscanning_repo_url: https://github.com/lfscanning/spdx-lfenergy
tac_member_list_url: https://lfenergy.org/about/people/#technical-advisory-council
lf_staff_list_url: https://lfenergy.org/about/people/#executive-leadership
mission_statement_url: https://lfenergy.org/about/why-lf-energy/ 
tac_agenda_url: https://github.com/orgs/lf-energy/projects/2

# Foundation Settings
foundation_name: 'LF Energy Foundation'
clotributor_name: "lfenergy"
membership_top_tier: 'Strategic'
favicon_ico: "css/img/favicon.png"
archived_lifecycle_stage: "Emeritus"

aux_links:
  "Need help or have a question? Contact us here":
    - "//servicedesk.lfenergy.org"
footer_content: Copyright &copy; The Linux Foundation&reg;. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/trademark-usage">Trademark Usage</a> page. Linux is a registered trademark of Linus Torvalds. <a href="http://www.linuxfoundation.org/privacy">Privacy Policy</a> and <a href="http://www.linuxfoundation.org/terms">Terms of Use</a>.

readme_index:
  with_frontmatter: true

ga_tracking: 361402579
ga_tracking_anonymize_ip: true

kramdown:
  input: GFM
  extensions:
    - autolink
  parse_block_html: true
  toc_levels: 2..6

plugins:
  - jekyll-redirect-from

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.0"

callouts:
  note:
    title: Note
    color: blue

defaults:
  -
    scope: 
      path: "meetings/*/README.md"
      type: "pages"
    values:
      title: My Title
      parent: Meetings
