name: Hosted Projects Resource Requests
description: | 
  For hosted projects and working groups only, use this form to submit a resource 
  or a funding request to the TAC for consideration.
title: "SUBJECT - Resource Request"
labels: ["help wanted"]
assignees: 
  - lfenergy
body:
  - type: markdown
    attributes:
      value: |
        For hosted projects and working groups only, use this form to submit a resource 
        or a funding request to the TAC for consideration. Details on the full process 
        are at https://tac.lfenergy.org/tools/resource_request.

        Please update `SUBJECT` in the title with a title for the request.
  - type: dropdown
    attributes:
      label: Request category
      description: Pick the option closest to the kind of request you have.
      multiple: false
      options:
        - Project websites
        - Project demo sandbox infrastructure
        - Documentation and technical writing resources/support
        - Release engineering support (CI/CD optimization, build tooling, etc.)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is this needed?
      description: Please provide background on the need, and explain why existing tools/resources are not sufficient for the need.
    validations:
      required: true
  - type: input
    attributes:
      label: When is this needed by?
      description: Please either provide a date or the name of an event.
    validations:
      required: true
  - type: input
    attributes:
      label: What are the projected costs for this?
      description: If applicable, provide a link to the AWS cost estimator.
    validations:
      required: true
  - type: input
    attributes:
      label: What else should the TAC and Governing Board know about this request
    validations:
      required: true
